AREAS_OF_STUDY = [
    "Anthropology",
    "Archaeology",
    "History",
    "Linguistics and Languages",
    "Philosophy",
    "Religion",
    "Culinary Arts",
    "Literature",
    "Performing Arts",
    "Visual Arts",
    "Economics",
    "Geography",
    "Ethnic and Cultural Studies",
    "Gender and Sexuality Studies",
    "Organizational Studies",
    "Political Science",
    "Psychology",
    "Sociology",
    "Biology",
    "Chemistry",
    "Earth Sciences",
    "Physics",
    "Astronomy",
    "Computer Science",
    "Logic",
    "Mathematics",
    "Agriculture",
    "Architecture and Design",
    "Business",
    "Divinity",
    "Education",
    "Engineering and Technology",
    "Environmental Studies and Forestry",
    "Family and Consumer Science",
    "Journalism",
    "Law",
    "Library and Museum Studies",
    "Medicine",
    "Military Sciences",
    "Public Administration",
    "Public Policy",
    "Social Work",
    "Transportation",
]

import random

def get_area_of_study():
    return random.choice(AREAS_OF_STUDY)