# Generated by Django 2.2.6 on 2019-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='locations',
            field=models.ManyToManyField(related_name='job_postings', to='core.Location'),
        ),
    ]
