export enum StudyType {
  BACHELOR = "BACHELOR",
  MASTER = "MASTER",
  DOCTORATE = "DOCTORATE",
  ASSOCIATE = "ASSOCIATE",
  CERTIFICATE = "CERTIFICATE",
  DIPLOMA = "DIPLOMA",
  COURSEWORK = "COURSEWORK",
}
