JOB_TITLES = [
    '.NET Developer',
    '1st Shift HR Representative',
    'Account Collector',
    'Account Coordinator',
    'Account Director',
    'Account Executive',
    'Account Management Coordinator',
    'Account Manager',
    'Account Representative',
    'Account Specialist',
    'Account Supervisor',
    'Accountant',
    'Accounting Clerk',
    'Accounting Manager',
    'Activation Consultant',
    'Actuarial Analyst',
    'Actuarial Assistant',
    'Actuarial Associate',
    'Actuarial Manager',
    'Actuary',
    'Adjuster',
    'Administrative Assistant',
    'Administrative Coordinator',
    'Administrative Director',
    'Administrative Manager',
    'Administrative Medical Assistant',
    'Administrative Services Coordinator',
    'Administrative Services Manager',
    'Administrative Services Officer',
    'Administrative Specialist',
    'Administrative Support Manager',
    'Administrative Support Supervisor',
    'Administrator',
    'Administrator for Nonprofit Organizations',
    'Admissions Clerk',
    'Admissions Director',
    'Admissions Representative',
    'Advertising Consultant',
    'Advertising Coordinator',
    'Advertising Director',
    'Advertising Sales Assistant',
    'Advertising Sales Representative',
    'Advocacy Director',
    'Agent',
    'Aides Supervisor',
    'Air Quality Engineer',
    'Air Traffic Controllers',
    'Aircraft Mechanic',
    'Aircraft Pilot',
    'Airline Pilot',
    'Airport Operations Crew Member',
    'Allocation Analyst',
    'Ambulatory Nurse',
    'Analyst',
    'Analytical Lab Technician',
    'Analytical Services Chemist',
    'Anesthesiologist',
    'Animator',
    'Apparel Production Coordinator',
    'Application Developer',
    'Application Support Analyst',
    'Applications Engineer',
    "Applications Specialist\u00e2\u20ac\u2039",
    'Appraisal Manager',
    'Appraiser',
    'Apprentice',
    'Apprentice Bartender',
    'Arbitrator',
    'Archaeological Technician',
    'Archaeologist',
    'Archaeologist',
    'Architect',
    'Area Brand Coordinator',
    'Area Director',
    'Area Manager',
    'Area Sales Manager',
    'Area Vertebrate Pest Advisor',
    'Art Director',
    'Assay Development Specialist',
    'Assembler',
    'Assembly Supervisor',
    'Assistant Account Executive',
    'Assistant Account Manager',
    'Assistant Administrator',
    'Assistant Admissions Director',
    'Assistant Brand Manager',
    'Assistant Broker',
    'Assistant Buyer',
    'Assistant Chef',
    'Assistant City Manager for Sustainable Development',
    'Assistant Customer Care Center Manager',
    'Assistant Director',
    'Assistant Director of Benefits',
    'Assistant Director of Employment',
    'Assistant Director of Human Resources',
    'Assistant Director of Nursing',
    'Assistant Field Technician',
    'Assistant General Manager',
    'Assistant HR Manager',
    'Assistant Kitchen Manager',
    'Assistant Marketing Director',
    'Assistant Media Buyer',
    'Assistant Media Planner',
    'Assistant Merchandise Manager',
    'Assistant Merchant',
    'Assistant Plant Manager',
    'Assistant Procurement Manager',
    'Assistant Product Manager',
    'Assistant Project Manager',
    'Assistant Sales Manager',
    'Assistant Store Director',
    'Assistant Store Manager',
    'Assistant Stylist',
    'Assistant Technician',
    'Assistant VP Human Resources',
    'Associate',
    'Associate Brand Manager',
    'Associate Broker',
    'Associate Buyer',
    'Associate Creative Director',
    'Associate Designer',
    'Associate Developer',
    'Associate Director of Human Resources',
    'Associate Marketing Director',
    'Associate Merchandise Buyer',
    'Associate Pastor',
    'Associate Producer',
    'Associate Product Manager',
    'Associate Professor',
    'Athletic Recruiter',
    'Athletic Scout',
    'Athletic Trainer',
    'Attorney',
    'Audiologist',
    'Auditing Clerk',
    'Auditor',
    'Automotive Credit Buyer',
    'Automotive Mechanic',
    'Automotive Parts Counter Person',
    'Automotive Product Specialist',
    'Automotive Sales Manager',
    'Automotive Sales Representative',
    'Automotive Service Technician',
    'Aviation Maintenance Worker',
    'B2B Corporate Sales',
    'Back Office Assistant',
    'Back Office Supervisor',
    'Backwaiter',
    'Baker',
    'Bakery-Cafe Associate',
    'Bank Teller',
    'Banquet Manager',
    'Banquet Server',
    'Bar Manager',
    'Bar Staff',
    'Barback',
    'Barista',
    'Bartender',
    'Bedding Designer',
    'Behavioral Health Charge Nurse',
    'Bell Attendant',
    'Bellhop',
    'Bellman',
    'Bellperson',
    'Benefit Coordinator',
    'Benefits Administrator',
    'Benefits Coordinator',
    'Benefits Counselor',
    'Benefits Officer',
    'Benefits Specialist',
    'Benefits and Work Comp Manager',
    'Bereavement Coordinator',
    'Bereavement Counselor',
    'Bike Tour Guide',
    'Bilingual Customer Service Representative',
    'Bilingual Retail Sales Representative',
    'Bill Collector',
    'Billing Clerk',
    'Billing Coordinator',
    'Billing Manager',
    'Billing Specialist',
    'Bioanalytical Scientist',
    'Biochemist',
    'Bioinformatics Research Scientist',
    'Biological Technician',
    'Biologist',
    'Biology Professor',
    'Biomedical Engineer',
    'Biomedical Technician',
    'Blogger',
    'Boiler Operator',
    'Boilermaker',
    'Bookbinders and bindery workers',
    'Bookkeeper',
    'Boutique Assistant',
    'Brand Ambassador',
    'Brand Assistant',
    'Brand Management Consultant',
    'Brand Manager',
    'Brand Strategist',
    'Brazer',
    'Bricklayer',
    'Broker',
    'Builder Operations Manager',
    'Building Inspector',
    'Building Maintenance Manager',
    'Building and Grounds Supervisor',
    'Bus Driver',
    'Bus Person',
    'Business Analyst',
    'Business Consultant',
    'Business Development Manager',
    'Business Development Representative',
    'Business Office Supervisor',
    'Business Service Representative',
    'Business System Analyst',
    'Busser',
    'Buyer',
    'Buyer',
    'Buyer Assistant',
    'Buyer Engagement Team Lead',
    'Buyer Trainee',
    'Buyer of Cosmetics',
    'Buyer of Girls Apparel',
    'Buyer-Planne',
    'CAA',
    'CAO',
    'CCO',
    'CDL Driver',
    'CDO',
    'CEO',
    'CFO',
    'CIO',
    'CISO',
    'CITO',
    'CMO',
    'CNC Machinist',
    'CNC Operator',
    'COO',
    'CPO',
    'CRO',
    'CSO',
    'CTO',
    'CUO',
    'Cab Driver',
    'Cabin Stewardess',
    'Cafe Manager',
    'Call Center Customer Support',
    'Call Center Lead',
    'Call Center Representative',
    'Call Center Supervisor',
    'Campaign Manager',
    'Campus Maintenance Manager',
    'Captain',
    'Cardiac Catheterization Lab Nurse',
    'Cardiovascular Operating Room Nurse',
    'Cardiovascular Technologist',
    'Carpenter',
    'Carpenter Apprentice',
    'Carrier Procurement Representative',
    'Case Manager',
    'Cashier',
    'Casual Restaurant Manager',
    'Category Acquisition Advisor',
    'Category Acquisition Director',
    'Category Acquisition Lead',
    'Category Acquisition Manager',
    'Category Attraction Specialist',
    'Category Buyer',
    'Category Engagement Advisor',
    'Category Identification Manager',
    'Category Manager',
    'Category Partner',
    'Category Sourcing Lead',
    'Category Sourcing Manager',
    'Category Sourcing Partner',
    'Catering Manager',
    'Catering Sales Manager',
    'Cell Biology Scientist',
    'Cell Line Development Manager',
    'Certified Medical Assistant',
    'Certified Nurse Assistant',
    'Certified Nursing Assistant',
    'Certified Pharmacy Technician',
    'Change Management Consultant',
    'Channel Partner Sales Executive',
    'Chaplain',
    'Chapter Relations Administrator',
    'Charge Nurse',
    'Chauffeur',
    'Chef',
    'Chef Manager',
    'Chemical Dependency Counselor',
    'Chemical Dependency Director',
    'Chemical Engineer',
    'Chemical Plant Operator',
    'Chemical Technician',
    'Chief Accounting Officer',
    'Chief Administrative Officer',
    'Chief Applications Architect',
    'Chief Association Executive',
    'Chief Category Officer',
    'Chief Compliance Officer',
    'Chief Contracting Officer',
    'Chief Data Officer',
    'Chief Development Officer',
    'Chief Executive Officer',
    'Chief Financial Officer',
    'Chief Happiness Officer',
    'Chief Human Resources Officer',
    'Chief Information Officer',
    'Chief Information Officer',
    'Chief Information Security Officer',
    'Chief Information Technology Officer',
    'Chief Investments Officer',
    'Chief Manufacturing Executive',
    'Chief Marketing Officer',
    'Chief Operating Officer',
    'Chief Operations Officer',
    'Chief People Officer',
    'Chief Procurement Officer',
    'Chief Product Officer',
    'Chief Quality Control Executive',
    'Chief Risk Officer',
    'Chief Security Officer',
    'Chief Technical Officer',
    'Chief Technology Officer',
    'Chief Underwriting Officer',
    'Child Care Worker',
    'Child Life Specialist',
    'Child Support Case Officer',
    'Childbirth Educator',
    'Chiropractor',
    'Civil Engineer',
    'Civil Engineering Supervisor',
    'Claims Adjuster',
    'Claims Analyst',
    'Claims Clerk',
    'Claims Examiner',
    'Claims Manager',
    'Claims Representative',
    'Claims Specialist',
    'Clean Energy Finance Manager',
    'Cleaning Crew',
    'Clerk',
    'Client Account Assistant',
    'Client Distribution Specialist',
    'Client Facing Human Resources Specialist',
    'Client Relations Associate',
    'Client Relations Manager',
    'Client Relations Representative',
    'Client Service Specialist',
    'Client Services Coordinator',
    'Client Services Manager',
    'Client Services Representative',
    'Client Success Manager',
    'Client Support Manager',
    'Climate Data Analyst',
    'Clinical Coordinator, Recovery Services',
    'Clinical Data Research',
    'Clinical Facilities Planning Manager',
    'Clinical Laboratory Technologist',
    'Clinical Liaison',
    'Clinical Nurse Manager',
    'Clinical Pharmacology Professor',
    'Clinical Pharmacy Assistant',
    'Clinical Research Associate',
    'Clinical Research Coordinator',
    'Clinical Research Director',
    'Clinical Reviewer',
    'Clinical Specialist',
    'Closing Agent',
    'Closing Coordinator',
    'Cloud Architect',
    'Cloud Consultant',
    'Cloud Product and Project Manager',
    'Cloud Services Developer',
    'Cloud Software and Network Engineer',
    'Cloud System Administrator',
    'Cloud System Engineer',
    'Coating, Painting, and Spraying Machine Operator',
    'Coder',
    'Coding Educator',
    'Coffee Tasting Room Assistant',
    'Collector',
    'Commercial Photographer',
    'Commercial Print Management Consultant',
    'Commercial Real Estate Broker',
    'Commercial Sales Representative',
    'Communications Assistant',
    'Communications Coordinator',
    'Communications Director',
    'Communications Editor',
    'Communications Manager',
    'Communications Representative',
    'Communications Specialist',
    'Community Health Director',
    'Community Manager',
    'Community Organizer',
    'Community Outreach Advocate',
    'Community Outreach Coordinator',
    'Community Outreach Specialist',
    'Community Relations Director',
    'Community Service Project Coordinator',
    'Compensation Analyst',
    'Compensation Consultant',
    'Compensation Survey Analyst',
    'Compliance Coordinator',
    'Compliance Director',
    'Compliance Technician',
    'Computational Chemistry Manager',
    'Computer Analyst',
    'Computer Control Programmer/Operator',
    'Computer Engineer',
    'Computer Network Architect',
    'Computer Programmer',
    'Computer Service Representative',
    'Computer Systems Analyst',
    'Computer Systems Manager',
    'Computer and Information Research Scientist',
    'Computer and Information Systems Manager',
    'Computing Consultant',
    'Concierge',
    'Concierge Agent',
    'Conciliator',
    'Concrete Finisher',
    'Concrete Laborers',
    'Conductor',
    'Conference Coordinator',
    'Configuration Analyst',
    'Conservation Technician',
    'Construction Assistant',
    'Construction Coordinator',
    'Construction Engineer',
    'Construction Foreman',
    'Construction Manager',
    'Construction Painter',
    'Construction Superintendent',
    'Construction Supervisor',
    'Construction Worker',
    'Consultant',
    'Consultant Employment Specialist',
    'Consulting Advisor',
    'Consulting Analyst',
    'Contact Center Help Desk',
    'Contact Center Representative',
    'Content Manager',
    'Content Marketing Manager',
    'Content Strategiest',
    'Content Strategist',
    'Content Writer',
    'Contract Administrator',
    'Contract Analyst',
    'Contract Drafting Legal Specialist',
    'Contract Manager',
    'Contract Recruiter',
    'Contract and Pricing Analyst',
    'Contracts Administrator',
    'Controller',
    'Controls Engineer',
    'Cook',
    'Coordinator',
    'Coordinator of Planned Giving',
    'Copy Center Professional',
    'Copy Writer',
    'Copywriter',
    'Corporate Buyer',
    'Corporate Communications Specialist',
    'Corporate Giving Director',
    'Corporate Giving Manager',
    'Corporate Procurement Lead',
    'Corporate Recruiter',
    'Corporate Sales Account Executive',
    'Corporate Sales Manager',
    'Corporate Trainer',
    'Corrections Officer',
    'Cost Engineer',
    'Counselor',
    'Courier',
    'Court Messenger',
    'Court Reporter',
    'Court Representative',
    'Court Transcriptionist',
    'Crane Operator',
    'Creative Assistant',
    'Creative Consultant',
    'Creative Director',
    'Credit Analyst',
    'Credit Clerk',
    'Crew',
    'Crew Member',
    'Critical Care Director',
    'Cruise Ship',
    'Culinary Services Supervisor',
    'Culinary Trainee',
    'Curated Merchant',
    'Custodial Customer Representative',
    'Custodial Manager',
    'Custodian',
    'Customer Account Director',
    'Customer Care Associate',
    'Customer Care Coordinator',
    'Customer Care Executive',
    'Customer Care Manager',
    'Customer Care Operator',
    'Customer Care Representative',
    'Customer Care Supervisor',
    'Customer Consultant',
    'Customer Interaction Management Specialist',
    'Customer Liaison Officer',
    'Customer Relationship Specialist',
    'Customer Service Agent',
    'Customer Service Ambassador',
    'Customer Service Asset Manager',
    'Customer Service Assistant',
    'Customer Service Associate',
    'Customer Service Engineer',
    'Customer Service Greeter',
    'Customer Service Improvement Consultant',
    'Customer Service Lead',
    'Customer Service Manager',
    'Customer Service Professional',
    'Customer Service Representative',
    'Customer Service Specialist',
    'Customer Service Strategist',
    'Customer Service Technician',
    'Customer Solution Manager',
    'Customer Solution Provider',
    'Customer Solution Representative',
    'Customer Support Administrator',
    'Customer Support Associate',
    'Customer Support Manager',
    'Customer Support Specialist',
    'Cutter',
    'Cyber Security Strategy Consultant',
    'Dairy Processing Equipment Operator',
    'Dairy Processing Equipment Repairer',
    'Data Center Support Specialist',
    'Data Entry',
    'Data Quality Manager',
    'Data Services Specialist',
    'Database Administrator',
    'Database Analyst',
    'Deck Officer',
    'Deckhand',
    'Delivery Drivers',
    'Delivery Helper',
    'Delivery Merchandiser Trainee',
    'Delivery/Bulk Merchandiser',
    'Dental Assistant',
    'Dental Hygienist',
    'Dentist',
    'Department Manager',
    'Deputy Director, Division of Lands and Waterways',
    'Deputy Head of Procurement',
    'Dermatology Nurse',
    'Design Assistant',
    'Design Associate',
    'Design Engineer',
    'Designer',
    'Desktop Support Manager',
    'Desktop Support Specialist',
    'Dessert Finisher',
    'Destination Wedding Photographer',
    'Destination Wedding Planner',
    'Developer',
    'Development Assistant',
    'Development Associate',
    'Development Coordinator',
    'Development Director',
    'Development Manager',
    'Development Officer',
    'Development Operations Assistant',
    'Development Technologist',
    'Diagnostic Medical Sonographer',
    'Dialysis Nurse',
    'Dietitian',
    'Digital Brand Manager',
    'Digital Communications Professional',
    'Digital Content Manager',
    'Digital Marketing Manager',
    'Digital Media Manager',
    'Digital Media Producer',
    'Digital Media Supervisor',
    'Digital Media and Advertising Coordinator',
    'Dining Room Manager',
    'Direct Buyer',
    'Direct Procurement Specialist',
    'Direct Sales Manager',
    'Direct Salesperson',
    'Director',
    'Director of  Customer Success and Satisfaction',
    'Director of Communications',
    'Director of Community',
    'Director of Development',
    'Director of Digital Marketing',
    'Director of Employment',
    'Director of Employment Services',
    'Director of Employment and Recruiting',
    'Director of Family Shelter',
    'Director of Hotel Operations',
    'Director of Hotel Sales',
    'Director of Human Resources',
    'Director of Inside Sales',
    'Director of Institutional Giving',
    'Director of Maintenance',
    'Director of Major Gifts',
    'Director of Marketing',
    'Director of Merchandise Planning and Allocation',
    'Director of National Sales',
    'Director of Nursing',
    'Director of Operations',
    'Director of Public Affairs',
    'Director of Public Relations',
    'Director of Purchasing',
    'Director of Quality Management',
    'Director of Real Estate',
    'Director of Rehabilitation',
    'Director of Sales',
    'Director of Social Media',
    'Director of Social Media Communications',
    'Director of Social Media Strategy',
    'Director of Sourcing',
    'Director of Special Initiatives',
    'Director of Stores',
    'Director of Strategic Communication',
    'Director of Talent',
    'Director of Talent Management',
    'Director of Technology',
    'Director, Communications Planning',
    'Director, Design and Product Development',
    'Director, Online Communications',
    'Director, Social Marketing and Brand Communications',
    'Director, Social Media Marketing',
    'Director, Social Media Relations',
    'Dishwasher',
    'Dispatcher',
    'Display Assistant',
    'Display Designer',
    'Display Manager',
    'Display Merchandiser',
    'Distribution Center Manager',
    'Distribution Director',
    'Distribution Manager',
    'Distribution Sales Representative',
    'District Human Resources Manager',
    'District Manager',
    'District Sales Manager',
    'District Technical Service Manager',
    'Division Manager',
    'Divisional Manager',
    'Doctor',
    'Document Coder',
    'Donor Relations Manager',
    'Driver',
    'Drug Evaluator',
    'Drug Regulatory Affairs Manager',
    'Dry Wall Finisher',
    'Dry wall Installer',
    'Duty Manager',
    'E-Learning Analyst',
    'E-Learning Coordinator',
    'E-Learning Director',
    'E-Learning Executive Director',
    'E-Learning Manager',
    'E-Learning Specialist',
    'ECommerce Coordinator',
    'ECommerce Planning Manager',
    'Easement Program Stewardship Coordinator',
    'Ecologist',
    'Ecology Team Leader',
    'Economic Consultant',
    'Economist',
    'Editor',
    'Editorial Assistant',
    'Editorial Photographer',
    'Education Specialist',
    'Educational Consultant',
    'Educational Travel Sales Representative',
    'Electric Home Appliance and Power Tool Repairer',
    'Electric Meter Installer and Repairer',
    'Electric Motor Assembler',
    'Electric/Electronics Technician',
    'Electrical Engineer',
    'Electrical Estimator',
    'Electrical Powerline Installer/Repairer',
    'Electrical Superintendent',
    'Electrical Utility Trouble Shooter',
    'Electrician',
    'Electrician Apprentice',
    'Electromechanical Technician',
    'Electronic Assembler',
    'Electronic Technician',
    'Elementary School Teacher',
    'Elevator Installer/Repairer',
    'Email Marketer',
    'Emergency Medical Technician',
    'Emergency Room Nurse',
    'Employee Benefits Account Manager',
    'Employee Benefits Law Specialist',
    'Employee Relations Associate Counsel',
    'Employee Relations Consultant',
    'Employee Relations Leader',
    'Employee Relations Manager',
    'Employee Relations Specialist',
    'Employee Retention Manager',
    'Employee Satisfaction Manager',
    'Employee and Labor Relations Consultant',
    'Employment Law Specialist',
    'Employment Supervisor',
    'Endoscopy Nurse',
    'Energy Auditor',
    'Energy Engineer',
    'Energy and Resource Conservation Manager',
    'Engagement Coordinator',
    'Engagement Manager',
    'Engineer',
    'English as a Second Language Teacher',
    'Enterprise Resources Planning Representative',
    'Enterprise Sales Representative',
    'Environmental Air Quality Consultant',
    'Environmental Analyst',
    'Environmental Attorney',
    'Environmental Audit Consultant',
    'Environmental Biologist',
    'Environmental Chemist',
    'Environmental Compliance Manager',
    'Environmental Compliance Technician',
    'Environmental Consultant',
    'Environmental Data Analyst',
    'Environmental Educator',
    'Environmental Emergencies Assistant',
    'Environmental Emergencies Planner',
    'Environmental Engineer',
    'Environmental Engineering Technician',
    'Environmental Field Consultant',
    'Environmental Health Scientist',
    'Environmental Health and Safety Specialist',
    'Environmental Planner',
    'Environmental Policy Analyst',
    'Environmental Project Analyst',
    'Environmental Project Manager',
    'Environmental Research Assistant',
    'Environmental Scientist',
    'Environmental Services Representative',
    'Environmental Specialist',
    'Environmental Technician',
    'Equipment Director',
    'Equipment Operator',
    'Equipment Sales Specialist',
    'Equipment Technician',
    'Espresso Beverage Maker',
    'Estimating Manager',
    'Estimator',
    'Event Coordinator',
    'Event Manager',
    'Event Planner',
    'Event Team Recruiter',
    'Events Coordinator',
    'Events Manager',
    'Examiner',
    'Executive Assistant',
    'Executive Buyer',
    'Executive Category Acquisition',
    'Executive Chef',
    'Executive Conference Manager',
    'Executive Director',
    'Executive Director of Nonprofit',
    'Executive Housekeeper',
    'Executive Meeting Manager',
    'Executive Merchandise Trainee',
    'Executive Recruiter',
    'Executive Services Administrator',
    'Executive Vice President',
    'Exercise physiologist',
    'Expediter',
    'Expeditor',
    'Exploration Director',
    'External Communications Manager',
    'Fabricator',
    'Facilities Director',
    'Facilities Management Executive',
    'Facilities Manager',
    'Facilities Planner',
    'Facilities Supervisor',
    'Facility Manager',
    'Factory Manager',
    'Family Nurse Practitioner',
    'Fashion Buyer',
    'Fashion Director',
    'Federal Government Relations Director',
    'Federal Health Consultant',
    'Federal Policy Director',
    'Fiberglass Laminator/Fabricator',
    'Field Adjuster',
    'Field Applications Specialist',
    'Field Crew Manager',
    'Field Engineer',
    'Field Operations Executive',
    'Field Operator',
    'Field Promotion Coordinator',
    'Field Recruiting Manager',
    'Field Research Assistant',
    'Field Sample Handler',
    'Field Service Coordinator',
    'Field Service Engineer',
    'Field Service Technician',
    'Field Supervisor',
    'Field Technical Consultant',
    'Field Technical Support Engineer',
    'Field Technician',
    'File Clerk',
    'Financial Advisor',
    'Financial Aid Director',
    'Financial Aid Representative',
    'Financial Analyst',
    'Financial Clerk',
    'Financial Consultant',
    'Financial Engineer',
    'Financial Planner',
    'Financial Public Relations Associate',
    'Financial Sales Assistant',
    'Fine Dining Restaurant Manager',
    'Fire Warden',
    'First Officer',
    'Fish and Wildlife Biologist',
    'Fixed Income Specialist',
    'Fleet Coordinator',
    'Fleet Manager',
    'Flight Attendant',
    'Flight Engineer',
    'Flight Instructor',
    'Flight Nurse',
    'Floor Area Manager',
    'Floor Assembler',
    'Floor Assembly Supervisor',
    'Floor Leader',
    'Floor Manager',
    'Floor Technician',
    'Food Runner',
    'Food Server',
    'Food Technologist',
    'Food and Beverage Manager',
    'Footwear Buyer',
    'Foreclosure Consultant',
    'Foreclosure Specialist',
    'Foreign Service Officer',
    'Forensic Chemist',
    'Forensic Scientist',
    'Forest Restoration Crew Member',
    'Forestry Technician',
    'Fork Lift Operator',
    'Foundation Assistant',
    'Foundation Director',
    'Foundation Specialist',
    'Framing Carpenter',
    'Franchise Development Manager',
    'Freelance Travel Writer',
    'Front Desk Agent',
    'Front Desk Associate',
    'Front Desk Clerk',
    'Front Desk Coordinator',
    'Front Desk Manager',
    'Front Desk Receptionist',
    'Front Desk Sales and Service Associate',
    'Front Desk Supervisor',
    'Front End Developer',
    'Front Manager',
    'Front Office Associate',
    'Front Office Attendant',
    'Front Office Clerk',
    'Functional Consultant',
    'Functional Leader',
    'Fund-Raiser',
    'Fundraising Consultant',
    'Fundraising Coordinator',
    'Fundraising Manager',
    'GIS Specialist',
    'Garage Cashier',
    'Gardener',
    'Gate Operations Staff',
    'Gene Editing Manager',
    'General Contractor Traveling Superintendent',
    'General Laborer',
    'General Maintenance Worker',
    'General Manager',
    'General Office Clerk',
    'Genetic Counselor',
    'Geologist',
    'Geologists',
    'Global Category Selection Manager',
    'Global Development Specialist',
    'Global Logistics Supervisor',
    'Global Procurement Sourcing Analyst',
    'Government Contract Consultant',
    'Graduate Buyer',
    'Grant Administrator',
    'Grant Coordinator',
    'Grant Manager',
    'Grant Proposal Manager',
    'Grant Writer',
    'Grant/Contracts Specialist',
    'Grants/Proposal Writer',
    'Graphic Artist',
    'Graphic Designer',
    'Graphic Production Artist',
    'Grassroots Organizer',
    'Greenskeeper',
    'Greeter',
    'Grill Cook',
    'Grinder',
    'Grounds Maintenance Worker',
    'Groundskeeper',
    'Groundskeepking Worker',
    'Groundwater Technician',
    'Group Sales Coordinator',
    'Group Sales Management',
    'Group Sales Manager',
    'Group and Events Sales Coordinator',
    'Guest Room Sales Manager',
    'Guest Service Agent',
    'Guest Service Representative',
    'Guest Services Agent',
    'Guest Services Associate',
    'Guest Services Coordinator',
    'Guest Services Manager',
    'Guest Services Supervisor',
    'Guidance Counselor',
    'HR Administrative Assistant',
    'HR Coordinator',
    'HR Generalist',
    'HR Manager',
    'HR Purchasing Specialist',
    'HRD/Training and Development Administrator',
    'HRD/Training and Development Analyst',
    'HRD/Training and Development Director',
    'HRD/Training and Development Manager',
    'HRD/Training and Development Specialist',
    'HRD/Training and Development Supervisor',
    'HRD/Training and Development Vice President',
    'HRIS Analyst',
    'HRIS Manager',
    'HVAC Apprentice',
    'HVAC Mechanic',
    'Handyman',
    'Hardware Designer',
    'Hardware Engineer',
    'Head of Category',
    'Head of Housekeeping',
    'Head of Procurement',
    'Health Educator',
    'Health Facilities Surveyor',
    'Health Research Assistant',
    'Health Services Manager',
    'Health Technology Assistant',
    'Health and Welfare Services Supervisor',
    'Healthcare Administrator',
    'Healthcare Change Capture Senior Staff Consultant',
    'Healthcare Consultant',
    'Healthcare Management',
    'Healthcare Management Consultant',
    'Healthcare Market Research Consultant',
    'Healthcare Sales Representative',
    'Healthcare Specialist',
    'Helicopter Pilot',
    'Help Desk Associate',
    'Help Desk Specialist',
    'Help Desk Support',
    'Help Desk Technician',
    'Hibachi Chef',
    'Home Health Aide',
    'Home Health Nurse',
    'Home Inspector',
    'Hospice Administrator',
    'Hospice Aide',
    'Hospice Counselor',
    'Hospice Nurse',
    'Hospice Supervisor',
    'Hospital Accounting Analyst',
    'Hospital Administrator',
    'Hospital Research Assistant',
    'Host',
    'Hostess',
    'Hotel Deposit Clerk',
    'Hotel Group Sales Manager',
    'House Supervisor Nurse',
    'Housekeeper',
    'Housekeeper Aide',
    'Housekeeping Dispatcher',
    'Housekeeping Manager',
    'Housekeeping Supervisor',
    'Housing Coordinator',
    'Housing Counselor',
    'Housing Program Manager',
    'Human Capital Consultant',
    'Human Factors Engineer',
    'Human Resource Information Systems Coordinator',
    'Human Resource Manager',
    'Human Resources Administrator',
    'Human Resources Adviser',
    'Human Resources Advocate',
    'Human Resources Analyst',
    'Human Resources Architect',
    'Human Resources Assistant',
    'Human Resources Associate',
    'Human Resources Business Partner',
    'Human Resources Champion',
    'Human Resources Clerk',
    'Human Resources Coach',
    'Human Resources Compensation Coordinator',
    'Human Resources Consultant',
    'Human Resources Coordinator',
    'Human Resources Director',
    'Human Resources Generalist',
    'Human Resources Manager',
    'Human Resources Officer',
    'Human Resources Representative',
    'Human Resources Specialist',
    'Human Resources Team Leader',
    'Human Resources Technician',
    'Human Resources and Safety Coordinator',
    'Human Services Consultant',
    'Human Services Worker',
    'Hunting Guide',
    'Hybrid Buyer',
    'Hydrogeologist',
    'IT Analyst',
    'IT Coordinator',
    'IT Director',
    'IT Manager',
    'IT Specialist',
    'IT Support Manager',
    'IT Support Specialist',
    'IT Support Staff',
    'IT Systems Administrator',
    'Illustrator',
    'Image Editor',
    'Immunology Scientist',
    'Implementation Consultant',
    'Import Production Coordinator',
    'Import/Export Clerk',
    'Import/Export Manager',
    'Import/Export Supervisor',
    'In Store Assistant Branch Manger',
    'Indirect Buyer',
    'Industrial Cleaner',
    'Industrial Designer',
    'Industrial Engineer',
    'Industrial Engineering Technician',
    'Industrial Machinery Mechanic',
    'Industrial Sales Representative',
    'Industrial Tractor Operator',
    'Industry Representative',
    'Information Clerk',
    'Information Security Analyst',
    'Information Technology Specialist',
    'Inside Sales Manager',
    'Inside Sales Representative',
    'Inside Salesperson',
    'Inspector',
    'Installation & Maintenance Executive',
    'Installation & Maintenance Technician Director',
    'Institutional Research Director',
    'Insurance Adjuster',
    'Insurance Agent',
    'Insurance Representative',
    'Insurance Sales Representative',
    'Intensive Care Nurse',
    'Interactive Media Associate',
    'Interactive Media Coordinator',
    'Interactive Media Manager',
    'Interagency Restoration Team Member',
    'Interior Aircraft Assembly Worker',
    'Internal Buyer',
    'Internal Communications Specialist',
    'International Admissions',
    'International Consultant',
    'International Education Coordinator',
    'International Journalism',
    'International Sourcing Agent',
    'International Travel Consultant',
    'Internet Marketing Coordinator',
    'Internet Marketing Director',
    'Internet Marketing Manager',
    'Internet Marketing Specialist',
    'Interpreter',
    'Interventional Radiology Nurse',
    'Intranet Specialist',
    'Intranet Support',
    'Inventory Analyst',
    'Inventory Associate',
    'Inventory Control Analyst',
    'Inventory Control Clerk',
    'Inventory Control Manager',
    'Inventory Control Supervisor',
    'Inventory Manager',
    'Inventory Planner',
    'Inventory Planner/Analyst',
    'Inventory Taker',
    'Investigator',
    'Investment Assistant',
    'Investment Banking Associate',
    'Investments Representative',
    'Iron Worker',
    'Janitor',
    'Java Developer',
    'Jewelry Product Manager',
    'Jig and Fixture Builder',
    'Job Developer',
    'Job Posting Specialist',
    'Joiner',
    'Journalist',
    'Judge',
    'Junior Accountant',
    'Junior Analyst',
    'Junior Art Director',
    'Junior Chemist',
    'Junior Engineer',
    'Junior Software Engineer',
    'Junior Writer',
    'Jury Consultant',
    'Juvenile Counselor',
    'Key Account Manager',
    'Kitchen Manager',
    'Kitchen Team Member',
    'Kitchen Worker',
    'Lab Technician',
    'Labor Union Organizer',
    'Labor and Delivery Nurse',
    'Laboratory Assistant',
    'Laboratory Instructor',
    'Laboratory Manager',
    'Laboratory Technician',
    'Laborer',
    'Lactation Consultant',
    'Land Conservation Fellow',
    'Land Manager',
    'Land Planning Analyst',
    'Landscaper',
    'Landscaping Worker',
    'Lateral Buyer',
    'Lateral Procurement Manager',
    'Laundry Attendant',
    'Law Firm Administrator',
    'Lawn Service Manager',
    'Lawyer',
    'Layette Designer',
    'Lead Buyer',
    'Lead Category Scout',
    'Lead Consulting Engineer',
    'Lead Cook',
    'Lead Housekeeper',
    'Lead Registered Nurse',
    'Lead Sourcing Consultant',
    'Lead Trainer',
    'Leadership Gifts Officer',
    'Leasing Materials Analyst',
    'Legal Aide/Assistant',
    'Legal Analyst',
    'Legal Consultant',
    'Legal Nurse Consultant',
    'Legal Records Manager',
    'Legal Secretary',
    'Legal Services Director',
    'Licensed Practical Nurse',
    'Licensed Real Estate Appraiser',
    'Licensed Sales Consultant',
    'Licensed Vocational Nurse',
    'Line Cook',
    'Lineman',
    'Litigation Docket Manager',
    'Litigation Support Director',
    'Living Skills Advisor',
    'Loan Documents Closer',
    'Loan Documents Coordinator',
    'Loan Officer',
    'Loan Processor',
    'Loan Underwriter',
    'Lobbyist',
    'Location Manager',
    'Location Scout',
    'Locksmith',
    'Locomotive Engineer',
    'Logistician',
    'Logistics Analyst',
    'Logistics Associate',
    'Logistics Coordinator',
    'Logistics Manager',
    'Logistics Specialist',
    'Logistics and Customer Service Manager',
    'Loss Control Consultant/Specialist',
    'Loss Prevention Specialist',
    'Luxury Fashion Recruiter',
    'MRI Technologist',
    'Machine Operator',
    'Machine Shop Maintenance Supervisor',
    'Machine Shop Production Supervisor',
    'Machine Tool Cutting Operator/Tender',
    'Machinery Maintenance Worker',
    'Machinists',
    'Magistrate',
    'Mail Clerk',
    'Mail Clerk Leader',
    'Mail room Personnel',
    'Maintenance Painter',
    'Maintenance Planner',
    'Maintenance Supervisor',
    'Maintenance Worker',
    'Maintenance and Service Manager',
    'Major Accounts Manager',
    'Major Gift Director.',
    'Major Gifts Officer',
    'Managed Care Coordinator',
    'Management Consultant',
    'Management Information Systems Director',
    'Management Specialist',
    'Management Trainee',
    'Manager',
    'Manager Digital and Social Media',
    'Manager IS Risk and Compliance',
    'Manager of Business Development',
    'Manager of Career and Employee Relations',
    'Manager of Customer Billing',
    'Manager of Retail Strategy Communications and Processes',
    'Manager or Supervisor',
    'Manager, Digital and Social Media',
    'Manager, Programs and Processes',
    'Manager, Research and Development',
    'Manager, Social Media',
    'Manager, Special Events',
    'Managing Editor',
    'Manufacturer Sales Representative',
    'Manufacturing Customer Service Representative',
    'Manufacturing Engineer',
    'Manufacturing Process Engineer',
    'Manufacturing Production Manager',
    'Manufacturing Technician',
    'Marine Cargo Inspector',
    'Marine Oiler',
    'Marine Operator',
    'Market Access Analyst',
    'Market Access Associate',
    'Market Development Manager',
    'Market Research Analyst',
    'Market Research Assistant',
    'Market Researcher',
    'Marketing Analyst',
    'Marketing Assistant',
    'Marketing Associate',
    'Marketing Communications Coordinator',
    'Marketing Communications Director',
    'Marketing Communications Manager',
    'Marketing Communications Specialist',
    'Marketing Consultant',
    'Marketing Coordinator',
    'Marketing Data Analyst',
    'Marketing Data Consultant',
    'Marketing Director',
    'Marketing Manager',
    'Marketing Officer',
    'Marketing Promotions Specialist',
    'Marketing Specialist',
    'Marketing and Communications Manager',
    'Marketing and Promotions Manager',
    'Mason',
    'Massage Therapist',
    'Master Electrician',
    'Master Plumber',
    'Master Scheduler',
    'Material Handler',
    'Material Recording Clerk',
    'Materials Control Manager',
    'Materials Handler',
    'Materials Handling Supervisor',
    'Materials Management Supervisor',
    'Materials Manager',
    'Materials Planner',
    'Mathematics Teacher',
    'Meat Manager',
    'Mechanic',
    'Mechanical Designer',
    'Mechanical Engineer',
    'Mechanical Technician',
    'Media Assistant',
    'Media Buyer',
    'Media Coordinator',
    'Media Director',
    'Media Planner',
    'Media Relations Coordinator',
    'Media Relations Director',
    'Media Relations Manager',
    'Media Researcher',
    'Media and Communications Manager',
    'Mediator',
    'Medicaid/Medicare Consultant',
    'Medical Administrative',
    'Medical Assistant',
    'Medical Assistant or Receptionist',
    'Medical Associate',
    'Medical Billing Specialist',
    'Medical Claims and Billing Specialist',
    'Medical Coder',
    'Medical Communications Director',
    'Medical Laboratory Technologist',
    'Medical Manager',
    'Medical Office Assistant',
    'Medical Office Manager',
    'Medical Office Specialist',
    'Medical Physics Researcher',
    'Medical Receptionist',
    'Medical Records Clerk',
    'Medical Records Director',
    'Medical Records Technician',
    'Medical Research Assistant',
    'Medical Research Technician',
    'Medical Sales',
    'Medical Sales Representative',
    'Medical Scientist',
    'Medical Secretary',
    'Medical Services Assistant',
    'Medical Social Worker',
    'Medical Surgery Nurse',
    'Medical Technician',
    'Medical Technologist',
    'Medical Transcriptionist',
    'Medical or Health Services Manager',
    'Meeting Assistant',
    'Meeting Concierge',
    'Meeting Coordinator',
    'Meeting Manager',
    'Meeting Planner',
    'Meeting Specialist',
    'Meeting/Event Manager',
    'Member Certification Manager',
    'Member Records Administrator',
    'Member Services Director',
    'Member Services Representative',
    'Membership Assistant',
    'Merchandise Analyst',
    'Merchandise Buyer',
    'Merchandise Coordinator',
    'Merchandise Manager',
    'Merchandise Planner',
    'Merchandise Supervisor',
    'Merchandiser',
    'Merchandising Assistant',
    'Merchant Assistant',
    'Merchant Mariners',
    'Metal Workers',
    'Microbiologist',
    'Millwright',
    'Mini-Bar Attendant',
    'Minister',
    'Ministers of Culture',
    'Mobile Director of Nursing Services',
    'Model',
    'Molecular Biologist',
    'Molecular Scientist',
    'Mortgage Advisor',
    'Mortgage Consultant',
    'Mortgage Coordinator',
    'Mortgage Loan Processor',
    'Mortgage Loan Underwriter',
    'Mortgage Professional',
    'Mortgage Specialist',
    'Motor Racer',
    'Motorboat Operator',
    'Multi-Media Communications Specialist',
    'National Accounts Sales Analyst',
    'National Accounts Sales General Manager',
    'National Accounts Sales Representative',
    'National Sales Manager',
    'National Training Manager',
    'Neonatal Intensive Care Nurse',
    'Network Administrator',
    'Network Architect',
    'Network Engineer',
    'Network Systems Administrator',
    'Network and Computer Systems Administrator',
    'New Media Coordinator',
    'Night Auditor',
    'Night Clerk',
    'Nonprofit Fundraiser',
    'Nuclear Medicine Technologist',
    'Nurse',
    'Nurse Aide',
    'Nurse Anesthetist',
    'Nurse Clinical Educator',
    'Nurse Consultant',
    'Nurse Informatics Analyst',
    'Nurse Manager',
    'Nurse Midwife',
    'Nurse Paralegal',
    'Nurse Practitioner',
    'Nursing Assistant',
    'Nursing Home Administrator',
    'Nutritionist',
    'Occupational Health Nurse',
    'Occupational Health and Safety Specialist',
    'Occupational Therapist',
    'Occupational Therapy Assistant',
    'Oceanographer',
    'Office Assistant',
    'Office Clerk',
    'Office Manager',
    'Office Nurse',
    'Office Support Manager',
    'Office Support Supervisor',
    'Oncology Nurse',
    'Oncology Researcher',
    'Online Activist',
    'Online Content Coordinator',
    'Online Customer Support',
    'Online Merchandise Coordinator',
    'Online Product Manager',
    'Operating Room Nurse',
    'Operations Analyst',
    'Operations Clerk',
    'Operations Manager',
    'Operations Research Analysis Manager',
    'Operations Section Manager',
    'Operations Security',
    'Operations Supervisor',
    'Operations Team Leader',
    'Operations Unit Manager',
    'Operator',
    'Optician',
    'Optometrist',
    'Order Entry/Processor',
    'Order Filler',
    'Order Picker',
    'Orderly Attendant',
    'Organic Lab Research Assistant',
    'Organic Lab Worker',
    'Organizational Development Administrator',
    'Organizational Development Analyst',
    'Organizational Development Consultant',
    'Organizational Development Director',
    'Organizational Development Manager',
    'Organizational Development Specialist',
    'Organizational Development VP',
    'Orthotist',
    'Outbound Calling Representative',
    'Outreach Coordinator',
    'Outreach RN',
    'Outside Sales Representative',
    'Package Handler',
    'Packaging Engineer',
    'Paint Specialist',
    'Painter',
    'Painting and Coating Worker',
    'Pantry Worker',
    'Paralegal',
    'Paramedic',
    'Park Resource Manager',
    'Pastor',
    'Patient Access Supervisor',
    'Patient Care Associate',
    'Patient Care Coordinator',
    'Patient Representative',
    'Patient Services Representative',
    'Patient Services Technician',
    'Pattern Maker',
    'Payroll Processing Specialist',
    'Payroll and Benefits Specialist',
    'Peace Corps Volunteer',
    'Pediatric Endocrinology Nurse',
    'Pediatric Intensive Care Nurse',
    'Pediatric Nurse',
    'Pediatric Nurse Practitioner',
    'Perioperative Nurse',
    'Personal Financial Adviser',
    'Personal Shopper',
    'Pest Control Technician',
    'Pesticide Handler',
    'Petroleum Engineer',
    'Pharmaceutical Assistant',
    'Pharmaceutical Marketing Assistant',
    'Pharmaceutical Research Analyst',
    'Pharmaceutical Research Assistant',
    'Pharmaceutical Research Technician',
    'Pharmaceutical Sales',
    'Pharmaceutical Sales Representative',
    'Pharmaceutical Technician',
    'Pharmacist',
    'Pharmacovigilance Supervisor',
    'Pharmacy Affairs Assistant',
    'Pharmacy Assistant',
    'Pharmacy Clerk',
    'Pharmacy Innovation Assistant',
    'Pharmacy Technician',
    'Phlebotomist',
    'Photo Editor',
    'Photographer',
    'Photographic Processor',
    'Photojournalist',
    'Physical Therapist',
    'Physical Therapist Assistant',
    'Physical Therapy Assistant',
    'Physician',
    'Physician Aide',
    'Physician Assistant',
    "Physician's Assistant",
    'Physics Teacher',
    'Pilot',
    'Pipe Fitter',
    'Pipefitter',
    'Pipeline Director',
    'Pipeline Executive',
    'Pipeline Maintenance Manager',
    'Pipeline Operations Manager',
    'Pipeline Technician',
    'Pipelines Manager',
    'Planned Gift Director',
    'Planned Giving Director',
    'Planner',
    'Planning Assistant',
    'Planning Manager',
    'Plant Accountant',
    'Plant Human Resources Manager',
    'Plant Manager',
    'Plant Operator',
    'Plastic Machine Worker',
    'Plumber',
    'Plumber Apprentice',
    'Podiatrist',
    'Policy Analyst',
    'Policy Processing Clerk',
    'Political Campaign Consultant',
    'Political Consultant',
    'Political Strategist',
    'Porter',
    'Post Anesthesia Nurse',
    'Postpartum Nurse',
    'Power Plant Dispatcher',
    'Power Plant Distributor',
    'Power Plant Operator',
    'Power Regulator',
    'Powerhouse Supervisor',
    'Precision Assembler',
    'Prep Cook',
    'Pricing Specialist',
    'Principal Consultant',
    'Principal Delivery Consultant',
    'Principal Procurement Specialist',
    'Printing Machine Operators',
    'Process Engineer',
    'Process Inspector',
    'Process Operator',
    'Process Research Manager',
    'Process/Product Design Engineer',
    'Processing Equipment Operations Supervisor',
    'Processing Worker',
    'Procurement Account Specialist',
    'Procurement Advisor',
    'Procurement Analyst',
    'Procurement Assistant',
    'Procurement Consultant',
    'Procurement Director',
    'Procurement Lead',
    'Procurement Manager',
    'Procurement Marketing Manager',
    'Procurement Operations Manager',
    'Procurement Partner',
    'Procurement Specialist',
    'Product Demonstrator',
    'Product Developer',
    'Product Development Engineering Manager',
    'Product Development Manager',
    'Product Engineer',
    'Product Manager',
    'Product Marketing Analyst',
    'Product Marketing Manager',
    'Product Planner',
    'Product Specialist',
    'Product Test Specialist',
    'Production Assistant',
    'Production Control Clerk',
    'Production Control Manager',
    'Production Coordinator',
    'Production Engineering Manager',
    'Production Foreman',
    'Production Manager',
    'Production Painter',
    'Production Planner/Scheduler',
    'Production Scheduler',
    'Production Sourcing Director',
    'Production Supervisor',
    'Production Team Leader',
    'Production Technician',
    'Production Test Supervisor',
    'Production Worker',
    'Professional Programs Assistant',
    'Program Administrator',
    'Program Assistant',
    'Program Associate',
    'Program Coordinator',
    'Program Director',
    'Program Manager',
    'Program Officer for Foundation',
    'Programmer',
    'Programmer Analyst',
    'Progressive Care Nurse',
    'Project Assistant',
    'Project Manager',
    'Project Monitoring Coordinator',
    'Project Purchaser',
    'Project Specialist',
    'Promotions Assistant',
    'Promotions Coordinator',
    'Promotions Director',
    'Property Manager',
    'Proposal Pricing Analyst',
    'Prosthetist',
    'Prototype Buyer',
    'Pruner',
    'Psychiatric Aide',
    'Psychiatric Nurse',
    'Psychiatric Nurse Practitioner',
    'Public Affairs Manager',
    'Public Affairs Specialist',
    'Public Health Nurse',
    'Public Health Specialist',
    'Public Information Assistant',
    'Public Information Officer',
    'Public Information Specialist',
    'Public Relations Assistant',
    'Public Relations Coordinator',
    'Public Relations Director',
    'Public Relations Manager',
    'Public Relations Representative',
    'Public Relations Specialist',
    'Public Transportation Inspector',
    'Publicist',
    'Publicity Assistant',
    'Publicity Director',
    'Publicity Manager',
    'Purchase Post-Closing Auditor',
    'Purchase Pre-Closing Auditor',
    'Purchaser',
    'Purchasing Agent',
    'Purchasing Agent/Buyer',
    'Purchasing Clerk',
    'Purchasing Consultant',
    'Purchasing Coordinator',
    'Purchasing Expeditor',
    'Purchasing Manager',
    'Purchasing Supervisor',
    'Quality Assistant',
    'Quality Assurance Engineer',
    'Quality Assurance Manager',
    'Quality Assurance Technologist',
    'Quality Control Analyst',
    'Quality Control Inspector',
    'Quality Control Manager',
    'Quality Control Supervisor',
    'Quality Coordinator',
    'Quality Engineer',
    'Quality Inspector',
    'Quality Manager',
    'Radiation Therapist',
    'Radiologic Technologist',
    'Rail Car Repairer',
    'Rail Yard Engineer',
    'Railroad Brake Operator',
    'Railroad Conductor',
    'Railroad Yard Worker',
    'Real Estate Agent',
    'Real Estate Analyst',
    'Real Estate Appraiser',
    'Real Estate Associate',
    'Real Estate Attorney',
    'Real Estate Clerk',
    'Real Estate Consultant',
    'Real Estate Manager',
    'Real Estate Specialist',
    'Real Estate Staff Attorney',
    'Realty Specialist',
    'Receptionist',
    'Records Management Analyst',
    'Recreational Therapist',
    'Recreational Therapy Director',
    'Recruiter',
    'Recruiting Assistant',
    'Recruiting Interviewer',
    'Recruiting Manager',
    'Recruiting and Sourcing Coordinator',
    'Recruitment Consultant',
    'Recruitment and Assessment Specialist',
    'Recruitment and Social Media Coordinator',
    'Refuse and Recyclable Material Collectors',
    'Regional Account Manager',
    'Regional Accounts Trainer',
    'Regional Brand Development Manager',
    'Regional Dealer Recruiter',
    'Regional Facilities Manager',
    'Regional Kidney Smart Educator',
    'Regional Manager',
    'Regional Operations Specialist',
    'Regional Sales Account Manager',
    'Regional Sales Executive',
    'Regional Sales Manager',
    'Registered Medical Assistant',
    'Registered Nurse',
    'Registered Nurse (RN)',
    'Registered Nurse (RN) Case Manager',
    'Registered Nurse (RN) Data Coordinator',
    'Registered Nurse (RN) First Assistant',
    'Registered Nurse (RN) Geriatric Care',
    'Registered Nurse (RN) Medical Inpatient Services',
    'Registered Nurse (RN) Patient Call Center',
    'Registered Nurse (RN) Student Health Services',
    'Registered Nurse (RN) Telephone Triage',
    'Registered Nurse (RN) Urgent Care',
    "Registered Nurse (RN) Women's Services",
    'Regulatory Affairs Associate',
    'Regulatory Affairs Director',
    'Regulatory Officer',
    'Rehabilitation Engineering Assistant',
    'Reimbursement Analyst',
    'Relationship Manager',
    'Reliability Engineer',
    'Renewable Energy Field Engineer',
    'Rental Representative',
    'Repair Worker',
    'Replenishment Analyst',
    'Research Assistant',
    'Research Associate',
    'Research Chemist',
    'Research Economist',
    'Research Official',
    'Research Scientist',
    'Research Specialist',
    'Research Team Leader',
    'Research Technician',
    'Research and Development Associate',
    'Research and Development Chemist',
    'Research and Development Director',
    'Research and Development Manager',
    'Research and Development Supervisor',
    'Research and Development Technician',
    'Research and Development Tester',
    'Research and Innovation Manager',
    'Researcher',
    'Reservations Agent',
    'Residential Living Assistant',
    'Resource Conservation Marketing Specialist',
    'Resource Consultant',
    'Resourcing Advisor',
    'Resourcing Associate',
    'Resourcing Director',
    'Resourcing Lead',
    'Resourcing Manager',
    'Resourcing Partner',
    'Resourcing Specialist',
    'Respiration (Inhalation) Therapist',
    'Response Services Representatives',
    'Restaurant General Manager',
    'Restaurant Manager',
    'Resteel ironworker',
    'Restorative Nurse',
    'Retail Administration Analyst',
    'Retail Analyst',
    'Retail Associate',
    'Retail Associate Store Manager',
    'Retail Buyer',
    'Retail Buyer',
    'Retail Clerk',
    'Retail Customer Service Associate',
    'Retail Fashion Recruiter',
    'Retail Food Service Manager',
    'Retail Footwear Buyer',
    'Retail Leadership Development Program',
    'Retail Loan Specialist',
    'Retail Management Trainee',
    'Retail Marketing Specialist',
    'Retail Personal Banker',
    'Retail Sales Associate',
    'Retail Sales Consultant',
    'Retail Sales Representative',
    'Retail Sales Worker',
    'Retail Salesperson',
    'Retail Security Officer',
    'Retail Store Manager',
    'Retail Store Planner',
    'Retail Team Leader',
    'Retail Trainee',
    'Retirement Plan Counselor',
    'Right of Way Agent',
    'Risk Consultant',
    'Risk Manager',
    'River Steward',
    'Roadie',
    'Roofer',
    'Room Attendant',
    'Room Service Manager',
    'Room Service Worker',
    'Route Driver',
    'Route Sales Representative',
    'Route Salesperson',
    'Route Supervisor',
    'SEO Manager',
    'STEM Career Advisor',
    'Safety Compliance and Recruitment Specialist',
    'Safety Consultant',
    'Safety Coordinator',
    'Safety Data Specialist',
    'Safety Director',
    'Safety Manager',
    'Safety Manager/Coordinator',
    'Safety Surveillance Associate',
    'Safety Technician',
    'Sailor',
    'Sales Account Executive',
    'Sales Agency Manager',
    'Sales Agent',
    'Sales Analyst',
    'Sales Assistant',
    'Sales Associate',
    'Sales Clerk',
    'Sales Consultant',
    'Sales Coordinator',
    'Sales Development Specialist',
    'Sales Director',
    'Sales Engineer',
    'Sales Executive',
    'Sales Inventory Analyst',
    'Sales Manager',
    'Sales Operation Coordinator',
    'Sales Representative',
    'Sales Representative - Territory Lead',
    'Sales Trainee',
    'Sales Worker',
    'Sales and Community Marketing Manager',
    'Sales and Marketing Coordinator',
    'Salesperson',
    'Sap Security Consultant',
    'Satellite Data Analyst',
    'Scheduler',
    'School Nurse',
    'Science Technician',
    'Scientific Artist',
    'Scientific Programmer',
    'Scientific Project Manager',
    'Scientific Writer',
    'Secretary',
    'Security Director',
    'Security Specialist',
    'Semiconductor Processor',
    'Senior Account Executive',
    'Senior Administrative Analyst',
    'Senior Administrative Assistant',
    'Senior Administrative Coordinator',
    'Senior Administrative Services Officer',
    'Senior Applications Engineer',
    'Senior Art Director',
    'Senior Benefits Consultant',
    'Senior Benefits Manager',
    'Senior Brand Manager',
    'Senior Buyer',
    'Senior Conservation Director',
    'Senior Coordinator',
    'Senior Database Administrator',
    'Senior Director of Development',
    'Senior Employee Benefits Consultant',
    'Senior Employee Benefits Manager',
    'Senior Executive Assistant',
    'Senior HR Specialist',
    'Senior Lync Consultant',
    'Senior Merchant',
    'Senior Network Architect',
    'Senior Network Engineer',
    'Senior Network System Administrator',
    'Senior Pharmacy Student',
    'Senior Planner',
    'Senior Product Manager',
    'Senior Programmer',
    'Senior Programmer Analyst',
    'Senior Purchasing Agent',
    'Senior Regulatory Specialist',
    'Senior Risk Control Consultant',
    'Senior Sales Manager',
    'Senior Sales Representative',
    'Senior Security Specialist',
    'Senior Software Engineer',
    'Senior Special Events Coordinator',
    'Senior Support Assistant',
    'Senior Support Specialist',
    'Senior System Administrator',
    'Senior System Analyst',
    'Senior System Architect',
    'Senior System Designer',
    'Senior Systems Analyst',
    'Senior Systems Software Engineer',
    'Senior Web Administrator',
    'Senior Web Developer',
    'Senior Wild Animal Keeper',
    'Server',
    'Service Administrator',
    'Service Advisor',
    'Service Consultant',
    'Service Delivery Manager',
    'Service Supervisor',
    'Shift Leader',
    'Shift Manager',
    'Shift Supervisor',
    'Shipping and Receiving Clerk',
    'Shipping and Receiving Manager',
    'Shipping and Receiving Supervisor',
    'Showroom Assistant',
    'Showroom Manager',
    'Showroom Model',
    'Showroom Representative',
    'Shuttle Car Operator',
    'Signal Worker',
    'Silicon Wafer Fabrication Operator',
    'Site Manager',
    'Social Media Account Executive',
    'Social Media Analyst',
    'Social Media Assistant',
    'Social Media Associate',
    'Social Media Coordinator',
    'Social Media Designer',
    'Social Media Editor',
    'Social Media Executive',
    'Social Media Manager',
    'Social Media Marketing Analyst',
    'Social Media Marketing Coordinator',
    'Social Media Marketing Coordinator',
    'Social Media Marketing Manager',
    'Social Media Producer',
    'Social Media Recruiter',
    'Social Media Specialist',
    'Social Media Specialist',
    'Social Media Strategist',
    'Social Services',
    'Social Services Director',
    'Social Work Manager',
    'Social Worker',
    'Software Architect',
    'Software Consultant',
    'Software Developer',
    'Software Engineer',
    'Software Engineering Assistant',
    'Software Implementation Consultant',
    'Software Quality Assurance Analyst',
    'Software Technical Support Analyst',
    'Soil Conservation Technician',
    'Solar Consultant',
    'Solar Energy Appointment Setters',
    'Solar Energy Design Engineer',
    'Solar Energy Sales Consultant',
    'Solar Installer',
    'Solar System Designer',
    'Solderer',
    'Solid Waste Field Technician',
    'Solutions Consultant',
    'Sonographer',
    'Sourcer',
    'Sourcing Advisor',
    'Sourcing Manager',
    'Sourcing Project Manager',
    'Sourcing Specialist',
    'Sous Chef',
    'Spares Coordinator',
    'Special Educator',
    'Special Events Coordinator',
    'Special Events Director',
    'Special Orders Technician',
    'Special Programs Buyer',
    'Special Programs Coordinator',
    'Special Projects Coordinator',
    'Specialty Sales Representative',
    'Speech-Language Pathologist',
    'Staff Assistant',
    'Staffing Consultant',
    'Staffing Coordinator',
    'Staffing and Employee Relations Consultant',
    'State Sales Manager',
    'Stationary Engineer',
    'Statistician',
    'Steamfitter',
    'Stem Cell Researcher',
    'Steward',
    'Stewardship Assistant',
    'Stock Clerk',
    'Stocker/Placer',
    'Store Director',
    'Store Manager',
    'Store Planner',
    'Strategic Account Manager',
    'Strategic Buyer',
    'Strategic Communications Manager',
    'Strategic Procurement Lead',
    'Strategic Sourcing Manager',
    'Strategy Consultant',
    'Streetcar Operator',
    'Structural Assembler',
    'Structural Biologist',
    'Structural Engineer',
    'Structural Ironworker',
    'Structural Metal fabricator',
    'Studio Photographer',
    'Style Specialist',
    'Stylist',
    'Subway Operator',
    'Superintendent',
    'Supervisor',
    'Supervisor of Provider Relations',
    'Supplier Quality Engineer',
    'Supplier Quality Specialist',
    'Supplier Relations Executive',
    'Supplier Relationship Manager',
    'Supply Chain Buyer',
    'Supply Technician',
    'Support Assistant',
    'Support Services Director',
    'Support Specialist',
    'Surface Mount Technology Machine Operator',
    'Surgeon',
    'Surgical Technologist',
    'Surveyor',
    'Sustainability Program Coordinator',
    'Sustainable Agriculture Program Manager',
    'Sustainable Design Specialist',
    'System Architect',
    'Systems Administrator',
    'Systems Analyst',
    'Systems Designer',
    "Systems Software Engineer\u00e2\u20ac\u2039",
    'Tactical Buyer',
    'Talent Acquisition Consultant',
    'Talent Acquisition Coordinator',
    'Talent Acquisition Manager',
    'Tax Advisor',
    'Taxi Driver',
    "Teacher's Assistant",
    'Team Leader',
    'Team Member',
    'Technical Application Specialist',
    'Technical Buyer',
    'Technical Designer',
    'Technical Operations Officer',
    'Technical Procurement Lead',
    'Technical Recruiter',
    'Technical Specialist',
    'Technical Support Engineer',
    'Technical Support Representatives',
    'Technical Support Specialist',
    'Technical Support Technician',
    'Technical Trainer',
    'Technical Writer',
    'Technology Consultant',
    'Technology Research Analyst',
    'Technology Research Manager',
    'Technology Specialist',
    'Teen Center Director',
    'Telecom Analyst',
    'Telecommunications Specialist',
    'Telemetry Nurse',
    'Telephone Support Specialist',
    'Teller',
    'Territory Business Manager',
    'Territory Manager',
    'Territory Sales Manager',
    'Territory Sales Representative',
    'Territory Service Representative',
    'Test Engineer',
    'Textile Fabric Colorist',
    'Therapeutic Director',
    'Therapist',
    'Title Coordinator',
    'Title Examiner',
    'Tool Crib Attendant',
    'Tool Room Supervisor',
    'Tool and Die Maker',
    'Tool, Die, and Gauge Maker',
    'Top Distribution Executive',
    'Top Inventory Control Executive',
    'Total Quality Management Director',
    'Total Quality Manager',
    'Tour Consultant',
    'Tour Guide',
    'Tour Manager',
    'Tour Promotions Assistant',
    'Touring Musician',
    'Toxicologist',
    'Trade Show Coordinator',
    'Traffic Clerk',
    'Traffic Director',
    'Traffic Manager',
    'Traffic Supervisor',
    'Traffic/Rate Analyst',
    'Trail Crew',
    'Train Conductor',
    'Train Crew Member',
    'Train Operator',
    'Trainer',
    'Training Assistant',
    'Training Coordinator',
    'Training Manager',
    'Training Specialist',
    'Training and Technical Assistance Coordinator',
    'Transaction Coordinator',
    'Transcriptionist',
    'Transportation Analyst',
    'Transportation Attendant',
    'Transportation Broker',
    'Transportation Coordinator',
    'Transportation Director',
    'Transportation Inspector',
    'Transportation Manager',
    'Transportation Planner',
    'Transportation Project Manager',
    'Transportation Supervisor',
    'Travel Agent',
    'Travel Coordinator',
    'Travel Manager',
    'Travel Reservations Specialist',
    'Travel Services Agent',
    'Traveling Nurse',
    'Treasurer',
    'Tree Trimmer and Pruner',
    'Trend Forecaster',
    'Trial Consultant',
    'Truck Driver',
    'Truck Driver Apprentice',
    'Truck Driver Supervisor',
    'Typist',
    'Ultrasonographer',
    'Underwriter',
    'Underwriter Assistant',
    'Underwriting Manager',
    'Union Organizer',
    'Union Relations',
    'VIP Travel Counselor',
    'Valet Attendant',
    'Valet Parker',
    'Valet Parking Attendant',
    'Van Driver',
    'Vehicle Return Associate',
    'Vehicle Washer/Equipment Cleaner',
    'Vendor Coordinator',
    'Vendor Manage',
    'Veterinarian',
    'Veterinary Assistant',
    'Veterinary Technologist',
    'Vice President for Marketing',
    'Vice President of Diversity',
    'Vice President of Human Resources',
    'Vice President of People',
    'Vice President of Talent Management',
    'Virtual Assistant',
    'Virtual Receptionist',
    'Visual Merchandiser',
    'Volunteer Coordinator',
    'Volunteer Director',
    'Volunteer Manager',
    'Volunteer Services Director',
    'Wafer Processing Technician',
    'Wait Staff',
    'Waiter',
    'Waitress',
    'Warehouse Associate',
    'Warehouse Manager',
    'Warehouse Worker',
    'Waste Treatment Plant Operator',
    'Waste Water Treatment Plant Manager',
    'Water Transportation Operator',
    'Water and Natural Resources Associate',
    'Wealth Management Advisor',
    'Web Administrator',
    'Web Applications Developer',
    'Web DesignerWeb Developer',
    'Webmaster',
    'Website Content Administrator',
    'Websphere Consultant',
    'Wedding Consultant',
    'Wedding Coordinator',
    'Wedding Sales Manager',
    'Weight Loss Consultant',
    'Welder',
    'Wellness Nurse',
    'Wetland Delineator',
    'Wetland Scientist',
    'Wholesale Sales Manager',
    'Wildlife Rehabilitation Program Intern',
    'Wildlife Rehabilitator',
    'Window Stylist',
    'Woodworker',
    'Word Processor',
    'Yardmaster',
    'eCommerce Marketing Director',
    'eCommerce Marketing Manager',
    'eCommerce Marketing Specialist',
    'eCommerce Recruiter',
    ]