# Generated by Django 2.2.6 on 2019-11-01 05:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('summary', models.TextField(blank=True)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('summary', models.TextField(blank=True)),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(blank=True, choices=[('NOVICE', 'Novice'), ('BEGINNER', 'Beginner'), ('COMPETENT', 'Competent'), ('PROFICIENT', 'Proficient'), ('EXPERT', 'Expert')], max_length=255)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(null=True)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('GITHUB', 'Github')], max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('MANDARIN', 'Mandarin'), ('SPANISH', 'Spanish'), ('ENGLISH', 'English'), ('HINDI', 'Hindi'), ('BENGALI', 'Bengali'), ('PORTUGUESE', 'Portuguese'), ('RUSSIAN', 'Russian'), ('JAPANESE', 'Japanese'), ('WESTERN_PUNJABI', 'Western Punjabi'), ('MARATHI', 'Marathi'), ('TELUGU', 'Telugu'), ('WU', 'Wu'), ('TURKISH', 'Turkish'), ('KOREAN', 'Korean'), ('FRENCH', 'French'), ('GERMAN', 'German'), ('VIETNAMESE', 'Vietnamese'), ('TAMIL', 'Tamil'), ('YUE', 'Yue'), ('URDU', 'Urdu'), ('JAVANESE', 'Javanese'), ('ITALIAN', 'Italian'), ('EGYPTIAN_ARABIC', 'Egyptian Arabic'), ('GUJARATI', 'Gujarati'), ('IRANIAN_PERSIAN', 'Iranian Persian'), ('BHOJPURI', 'Bhojpuri'), ('MIN_NAN', 'Min Nan'), ('HAKKA', 'Hakka'), ('JINYU', 'Jinyu'), ('HAUSA', 'Hausa'), ('KANNADA', 'Kannada'), ('INDONESIAN', 'Indonesian'), ('POLISH', 'Polish'), ('YORUBA', 'Yoruba'), ('XIANG_CHINESE', 'Xiang Chinese'), ('MALAYALAM', 'Malayalam'), ('ODIA', 'Odia'), ('MAITHILI', 'Maithili'), ('BURMESE', 'Burmese'), ('EASTERN_PUNJABI', 'Eastern Punjabi'), ('SUNDA', 'Sunda'), ('SUDANESE_ARABIC', 'Sudanese Arabic'), ('ALGERIAN_ARABIC', 'Algerian Arabic'), ('MOROCCAN_ARABIC', 'Moroccan Arabic'), ('UKRANIAN', 'Ukranian'), ('IGBO', 'Igbo'), ('NORTHERN_UZBEK', 'Northern Uzbek'), ('SINDHI', 'Sindhi'), ('NORTH_LEVANTINE_ARABIC', 'North Levantine Arabic'), ('ROMANIAN', 'Romanian'), ('TAGALOG', 'Tagalog'), ('DUTCH', 'Dutch'), ('SAIDI_ARABIC', "Sa'idi Arabic"), ('GAN', 'Gan'), ('AMHARIC', 'Amharic'), ('NORTHERN_PASHTO', 'Northern Pashto'), ('MAGAHI', 'Magahi'), ('THAI', 'Thai'), ('SARAIKI', 'Saraiki'), ('KHMER', 'Khmer'), ('CHHATTISGARHI', 'Chhattisgarhi'), ('SOMALI', 'Somali'), ('MALAY', 'Malay'), ('CEBUANO', 'Cebuano'), ('NEPALI', 'Nepali'), ('MESOPOTAMIAN_ARABIC', 'Mesopotamian Arabic'), ('ASSAMESE', 'Assamese'), ('SINHALA', 'Sinhala'), ('NORTHER_KURDISH', 'Northern Kurdish'), ('HEJAZI_ARABIC', 'Hejazi Arabic'), ('NIGERIAN_FULFULDE', 'Nigerian Fulfulde'), ('BAVARIAN', 'Bavarian'), ('SOUTH_AZERBAIJANI', 'South Azerbaijani'), ('GREEK', 'Greek'), ('CHITTAGONIAN', 'Chittagonian'), ('KAZAKH', 'Kazakh'), ('DECCAN', 'Deccan'), ('HUNGARIAN', 'Hungarian'), ('KINYARWANDA', 'Kinyarwanda'), ('ZULU', 'Zulu'), ('SOUTH_LEVANTINE_ARABIC', 'South Levantine Arabic'), ('TUNISIAN_ARABIC', 'Tunisian Arabic'), ('SANAANI_SPOKEN_ARABIC', 'Sanaani Spoken Arabic'), ('MIN_BEI_CHINESE', 'Min Bei Chinese'), ('SOUTHERN_PASHTO', 'Southern Pashto'), ('RUNDI', 'Rundi'), ('CZECH', 'Czech'), ('TAIZZI_ADENI_ARABIC', "Ta'izzi-Adeni Arabic"), ('UYGHUR', 'Uyghur'), ('MIN_DONG_CHINESE', 'Min Dong Chinese'), ('SYLHETI', 'Sylheti')], max_length=255)),
                ('fluency', models.CharField(blank=True, choices=[('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('SUPERIOR', 'Superior')], max_length=255)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('study_type', models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Doctorate'), ('ASSOCIATE', 'Associate'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('COURSEWORK', 'Coursework')], max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('courses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(null=True)),
                ('awarder', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('resume', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resume.Resume')),
            ],
        ),
    ]
