STUDY_TYPES = (
    ('BACHELOR', 'Bachelor'),
    ('MASTER', 'Master'),
    ('DOCTORATE', 'Doctorate'),
    ('ASSOCIATE', 'Associate'),
    ('CERTIFICATE', 'Certificate'),
    ('DIPLOMA', 'Diploma'),
    ('COURSEWORK', 'Coursework')
)

MASTERY_LEVELS = (
    ('NOVICE', 'Novice'),
    ('BEGINNER', 'Beginner'),
    ('COMPETENT', 'Competent'),
    ('PROFICIENT', 'Proficient'),
    ('EXPERT', 'Expert'),
)

FLUENCY_LEVELS = (
    ('NOVICE', 'Novice'),
    ('INTERMEDIATE', 'Intermediate'),
    ('ADVANCED', 'Advanced'),
    ('SUPERIOR', 'Superior'),
)

ONLINE_NETWORKS = (
    ('FACEBOOK', 'Facebook'),
    ('TWITTER', 'Twitter'),
    ('GITHUB', 'Github'),
)

# https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers
LANGUAGES = (
    ('MANDARIN', 'Mandarin'),
    ('SPANISH', 'Spanish'),
    ('ENGLISH', 'English'),
    ('HINDI', 'Hindi'),
    ('BENGALI', 'Bengali'),
    ('PORTUGUESE', 'Portuguese'),
    ('RUSSIAN', 'Russian'),
    ('JAPANESE', 'Japanese'),
    ('WESTERN_PUNJABI', 'Western Punjabi'),
    ('MARATHI', 'Marathi'),
    ('TELUGU', 'Telugu'),
    ('WU', 'Wu'),
    ('TURKISH', 'Turkish'),
    ('KOREAN', 'Korean'),
    ('FRENCH', 'French'),
    ('GERMAN', 'German'),
    ('VIETNAMESE', 'Vietnamese'),
    ('TAMIL', 'Tamil'),
    ('YUE', 'Yue'),
    ('URDU', 'Urdu'),
    ('JAVANESE', 'Javanese'),
    ('ITALIAN', 'Italian'),
    ('EGYPTIAN_ARABIC', 'Egyptian Arabic'),
    ('GUJARATI', 'Gujarati'),
    ('IRANIAN_PERSIAN', 'Iranian Persian'),
    ('BHOJPURI', 'Bhojpuri'),
    ('MIN_NAN', 'Min Nan'),
    ('HAKKA', 'Hakka'),
    ('JINYU', 'Jinyu'),
    ('HAUSA', 'Hausa'),
    ('KANNADA', 'Kannada'),
    ('INDONESIAN', 'Indonesian'),
    ('POLISH', 'Polish'),
    ('YORUBA', 'Yoruba'),
    ('XIANG_CHINESE', 'Xiang Chinese'),
    ('MALAYALAM', 'Malayalam'),
    ('ODIA', 'Odia'),
    ('MAITHILI', 'Maithili'),
    ('BURMESE', 'Burmese'),
    ('EASTERN_PUNJABI', 'Eastern Punjabi'),
    ('SUNDA', 'Sunda'),
    ('SUDANESE_ARABIC', 'Sudanese Arabic'),
    ('ALGERIAN_ARABIC', 'Algerian Arabic'),
    ('MOROCCAN_ARABIC', 'Moroccan Arabic'),
    ('UKRANIAN', 'Ukranian'),
    ('IGBO', 'Igbo'),
    ('NORTHERN_UZBEK', 'Northern Uzbek'),
    ('SINDHI', 'Sindhi'),
    ('NORTH_LEVANTINE_ARABIC', 'North Levantine Arabic'),
    ('ROMANIAN', 'Romanian'),
    ('TAGALOG', 'Tagalog'),
    ('DUTCH', 'Dutch'),
    ('SAIDI_ARABIC', 'Sa\'idi Arabic'),
    ('GAN', 'Gan'),
    ('AMHARIC', 'Amharic'),
    ('NORTHERN_PASHTO', 'Northern Pashto'),
    ('MAGAHI', 'Magahi'),
    ('THAI', 'Thai'),
    ('SARAIKI', 'Saraiki'),
    ('KHMER', 'Khmer'),
    ('CHHATTISGARHI', 'Chhattisgarhi'),
    ('SOMALI', 'Somali'),
    ('MALAY', 'Malay'),
    ('CEBUANO', 'Cebuano'),
    ('NEPALI', 'Nepali'),
    ('MESOPOTAMIAN_ARABIC', 'Mesopotamian Arabic'),
    ('ASSAMESE', 'Assamese'),
    ('SINHALA', 'Sinhala'),
    ('NORTHER_KURDISH', 'Northern Kurdish'),
    ('HEJAZI_ARABIC', 'Hejazi Arabic'),
    ('NIGERIAN_FULFULDE', 'Nigerian Fulfulde'),
    ('BAVARIAN', 'Bavarian'),
    ('SOUTH_AZERBAIJANI', 'South Azerbaijani'),
    ('GREEK', 'Greek'),
    ('CHITTAGONIAN', 'Chittagonian'),
    ('KAZAKH', 'Kazakh'),
    ('DECCAN', 'Deccan'),
    ('HUNGARIAN', 'Hungarian'),
    ('KINYARWANDA', 'Kinyarwanda'),
    ('ZULU', 'Zulu'),
    ('SOUTH_LEVANTINE_ARABIC', 'South Levantine Arabic'),
    ('TUNISIAN_ARABIC', 'Tunisian Arabic'),
    ('SANAANI_SPOKEN_ARABIC', 'Sanaani Spoken Arabic'),
    ('MIN_BEI_CHINESE', 'Min Bei Chinese'),
    ('SOUTHERN_PASHTO', 'Southern Pashto'),
    ('RUNDI', 'Rundi'),
    ('CZECH', 'Czech'),
    ('TAIZZI_ADENI_ARABIC', 'Ta\'izzi-Adeni Arabic'),
    ('UYGHUR', 'Uyghur'),
    ('MIN_DONG_CHINESE', 'Min Dong Chinese'),
    ('SYLHETI', 'Sylheti'),
)

COUNTRIES = (
    ('AFGHANISTAN', 'Afghanistan'),
    ('ALBANIA', 'Albania'),
    ('ALGERIA', 'Algeria'),
    ('ANDORRA', 'Andorra'),
    ('ANGOLA', 'Angola'),
    ('ANTIGUA_AND_BARBUDA', 'Antigua and Barbuda'),
    ('ARGENTINA', 'Argentina'),
    ('ARMENIA', 'Armenia'),
    ('AUSTRALIA', 'Australia'),
    ('AUSTRIA', 'Austria'),
    ('AZERBAIJAN', 'Azerbaijan'),
    ('BAHAMAS', 'The Bahamas'),
    ('BAHRAIN', 'Bahrain'),
    ('BANGLADESH', 'Bangladesh'),
    ('BARBADOS', 'Barbados'),
    ('BELARUS', 'Belarus'),
    ('BELGIUM', 'Belgium'),
    ('BELIZE', 'Belize'),
    ('BENIN', 'Benin'),
    ('BHUTAN', 'Bhutan'),
    ('BOLIVIA', 'Bolivia'),
    ('BOSNIA_AND_HERZEGOVINA', 'Bosnia and Herzegovina'),
    ('BOTSWANA', 'Botswana'),
    ('BRAZIL', 'Brazil'),
    ('BRUNEI', 'Brunei'),
    ('BULGARIA', 'Bulgaria'),
    ('BURKINA_FASO', 'Burkina Faso'),
    ('BURUNDI', 'Burundi'),
    ('CABO_VERDE', 'Cabo Verde'),
    ('CAMBODIA', 'Cambodia'),
    ('CAMEROON', 'Cameroon'),
    ('CANADA', 'Canada'),
    ('CENTRAL_AFRICAN_REPUBLIC', 'Central African Republic'),
    ('CHAD', 'Chad'),
    ('CHILE', 'Chile'),
    ('CHINA', 'China'),
    ('COLOMBIA', 'Colombia'),
    ('COMOROS', 'Comoros'),
    ('DEMOCRATIC_REPUBLIC_OF_THE_CONGO', 'Democratic Republic of the Congo'),
    ('REPUBLIC_OF_THE_CONGO', 'Republic of the Congo'),
    ('COSTA_RICA', 'Costa Rica'),
    ('COTE_D_IVOIRE', 'Côte d’Ivoire'),
    ('CROATIA', 'Croatia'),
    ('CUBA', 'Cuba'),
    ('CYPRUS', 'Cyprus'),
    ('CZECH_REPUBLIC', 'Czech Republic'),
    ('DENMARK', 'Denmark'),
    ('DJIBOUTI', 'Djibouti'),
    ('DOMINICA', 'Dominica'),
    ('DOMINICAN_REPUBLIC', 'Dominican Republic'),
    ('EAST_TIMOR', 'East Timor (Timor-Leste)'),
    ('ECUADOR', 'Ecuador'),
    ('EGYPT', 'Egypt'),
    ('EL_SALVADOR', 'El Salvador'),
    ('EQUATORIAL_GUINEA', 'Equatorial Guinea'),
    ('ERITREA', 'Eritrea'),
    ('ESTONIA', 'Estonia'),
    ('ESWATINI', 'Eswatini'),
    ('ETHIOPIA', 'Ethiopia'),
    ('FIJI', 'Fiji'),
    ('FINLAND', 'Finland'),
    ('FRANCE', 'France'),
    ('GABON', 'Gabon'),
    ('GAMBIA', 'The Gambia'),
    ('GEORGIA', 'Georgia'),
    ('GERMANY', 'Germany'),
    ('GHANA', 'Ghana'),
    ('GREECE', 'Greece'),
    ('GRENADA', 'Grenada'),
    ('GUATEMALA', 'Guatemala'),
    ('GUINEA', 'Guinea'),
    ('GUINEA_BISSAU', 'Guinea-Bissau'),
    ('GUYANA', 'Guyana'),
    ('HAITI', 'Haiti'),
    ('HONDURAS', 'Honduras'),
    ('HUNGARY', 'Hungary'),
    ('ICELAND', 'Iceland'),
    ('INDIA', 'India'),
    ('INDONESIA', 'Indonesia'),
    ('IRAN', 'Iran'),
    ('IRAQ', 'Iraq'),
    ('IRELAND', 'Ireland'),
    ('ISRAEL', 'Israel'),
    ('ITALY', 'Italy'),
    ('JAMAICA', 'Jamaica'),
    ('JAPAN', 'Japan'),
    ('JORDAN', 'Jordan'),
    ('KAZAKHSTAN', 'Kazakhstan'),
    ('KENYA', 'Kenya'),
    ('KIRIBATI', 'Kiribati'),
    ('NORTH_KOREA', 'North Korea'),
    ('SOUTH_KOREA', 'South Korea'),
    ('KOSOVO', 'Kosovo'),
    ('KUWAIT', 'Kuwait'),
    ('KYRGYZSTAN', 'Kyrgyzstan'),
    ('LAOS', 'Laos'),
    ('LATVIA', 'Latvia'),
    ('LEBANON', 'Lebanon'),
    ('LESOTHO', 'Lesotho'),
    ('LIBERIA', 'Liberia'),
    ('LIBYA', 'Libya'),
    ('LIECHTENSTEIN', 'Liechtenstein'),
    ('LITHUANIA', 'Lithuania'),
    ('LUXEMBOURG', 'Luxembourg'),
    ('MADAGASCAR', 'Madagascar'),
    ('MALAWI', 'Malawi'),
    ('MALAYSIA', 'Malaysia'),
    ('MALDIVES', 'Maldives'),
    ('MALI', 'Mali'),
    ('MALTA', 'Malta'),
    ('MARSHALL_ISLANDS', 'Marshall Islands'),
    ('MAURITANIA', 'Mauritania'),
    ('MAURITIUS', 'Mauritius'),
    ('MEXICO', 'Mexico'),
    ('FEDERATED_STATES_OF_MICRONESIA', 'Federated States of Micronesia'),
    ('MOLDOVA', 'Moldova'),
    ('MONACO', 'Monaco'),
    ('MONGOLIA', 'Mongolia'),
    ('MONTENEGRO', 'Montenegro'),
    ('MOROCCO', 'Morocco'),
    ('MOZAMBIQUE', 'Mozambique'),
    ('MYANMAR', 'Myanmar (Burma)'),
    ('NAMIBIA', 'Namibia'),
    ('NAURU', 'Nauru'),
    ('NEPAL', 'Nepal'),
    ('NETHERLANDS', 'Netherlands'),
    ('NEW_ZEALAND', 'New Zealand'),
    ('NICARAGUA', 'Nicaragua'),
    ('NIGER', 'Niger'),
    ('NIGERIA', 'Nigeria'),
    ('NORTH_MACEDONIA', 'North Macedonia'),
    ('NORWAY', 'Norway'),
    ('OMAN', 'Oman'),
    ('PAKISTAN', 'Pakistan'),
    ('PALAU', 'Palau'),
    ('PANAMA', 'Panama'),
    ('PAPUA_NEW_GUINEA', 'Papua New Guinea'),
    ('PARAGUAY', 'Paraguay'),
    ('PERU', 'Peru'),
    ('PHILIPPINES', 'Philippines'),
    ('POLAND', 'Poland'),
    ('PORTUGAL', 'Portugal'),
    ('QATAR', 'Qatar'),
    ('ROMANIA', 'Romania'),
    ('RUSSIA', 'Russia'),
    ('RWANDA', 'Rwanda'),
    ('SAINT_KITTS_AND_NEVIS', 'Saint Kitts and Nevis'),
    ('SAINT_LUCIA', 'Saint Lucia'),
    ('SAINT_VINCENT_AND_THE_GRENADINES', 'Saint Vincent and the Grenadines'),
    ('SAMOA', 'Samoa'),
    ('SAN_MARINO', 'San Marino'),
    ('SAO_TOME_AND_PRINCIPE', 'Sao Tome and Principe'),
    ('SAUDI_ARABIA', 'Saudi Arabia'),
    ('SENEGAL', 'Senegal'),
    ('SERBIA', 'Serbia'),
    ('SEYCHELLES', 'Seychelles'),
    ('SIERRA_LEONE', 'Sierra Leone'),
    ('SINGAPORE', 'Singapore'),
    ('SLOVAKIA', 'Slovakia'),
    ('SLOVENIA', 'Slovenia'),
    ('SOLOMON_ISLANDS', 'Solomon Islands'),
    ('SOMALIA', 'Somalia'),
    ('SOUTH_AFRICA', 'South Africa'),
    ('SPAIN', 'Spain'),
    ('SRI_LANKA', 'Sri Lanka'),
    ('SUDAN', 'Sudan'),
    ('SOUTH_SUDAN', 'South Sudan'),
    ('SURINAME', 'Suriname'),
    ('SWEDEN', 'Sweden'),
    ('SWITZERLAND', 'Switzerland'),
    ('SYRIA', 'Syria'),
    ('TAIWAN', 'Taiwan'),
    ('TAJIKISTAN', 'Tajikistan'),
    ('TANZANIA', 'Tanzania'),
    ('THAILAND', 'Thailand'),
    ('TOGO', 'Togo'),
    ('TONGA', 'Tonga'),
    ('TRINIDAD_AND_TOBAGO', 'Trinidad and Tobago'),
    ('TUNISIA', 'Tunisia'),
    ('TURKEY', 'Turkey'),
    ('TURKMENISTAN', 'Turkmenistan'),
    ('TUVALU', 'Tuvalu'),
    ('UGANDA', 'Uganda'),
    ('UKRAINE', 'Ukraine'),
    ('UNITED_ARAB_EMIRATES', 'United Arab Emirates'),
    ('UNITED_KINGDOM', 'United Kingdom'),
    ('UNITED_STATES', 'United States'),
    ('URUGUAY', 'Uruguay'),
    ('UZBEKISTAN', 'Uzbekistan'),
    ('VANUATU', 'Vanuatu'),
    ('VATICAN_CITY', 'Vatican City'),
    ('VENEZUELA', 'Venezuela'),
    ('VIETNAM', 'Vietnam'),
    ('YEMEN', 'Yemen'),
    ('ZAMBIA', 'Zambia'),
    ('ZIMBABWE', 'Zimbabwe'),
)

# https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States
STATES = (
    ('ALABAMA', 'Alabama'),
    ('ALASKA', 'Alaska'),
    ('ARIZONA', 'Arizona'),
    ('ARKANSAS', 'Arkansas'),
    ('CALIFORNIA', 'California'),
    ('COLORADO', 'Colorado'),
    ('CONNECTICUT', 'Connecticut'),
    ('DELAWARE', 'Delaware'),
    ('FLORIDA', 'Florida'),
    ('GEORGIA', 'Georgia'),
    ('HAWAII', 'Hawaii'),
    ('IDAHO', 'Idaho'),
    ('ILLINOIS', 'Illinois'),
    ('INDIANA', 'Indiana'),
    ('IOWA', 'Iowa'),
    ('KANSAS', 'Kansas'),
    ('KENTUCKY', 'Kentucky'),
    ('LOUISIANA', 'Louisiana'),
    ('MAINE', 'Maine'),
    ('MARYLAND', 'Maryland'),
    ('MASSACHUSETTS', 'Massachusetts'),
    ('MICHIGAN', 'Michigan'),
    ('MINNESOTA', 'Minnesota'),
    ('MISSISSIPPI', 'Mississippi'),
    ('MISSOURI', 'Missouri'),
    ('MONTANA', 'Montana'),
    ('NEBRASKA', 'Nebraska'),
    ('NEVADA', 'Nevada'),
    ('NEW_HAMPSHIRE', 'New Hampshire'),
    ('NEW_JERSEY', 'New Jersey'),
    ('NEW_MEXICO', 'New Mexico'),
    ('NEW_YORK', 'New York'),
    ('NORTH_CAROLINA', 'North Carolina'),
    ('NORTH_DAKOTA', 'North Dakota'),
    ('OHIO', 'Ohio'),
    ('OKLAHOMA', 'Oklahoma'),
    ('OREGON', 'Oregon'),
    ('PENNSYLVANIA', 'Pennsylvania'),
    ('RHODE_ISLAND', 'Rhode Island'),
    ('SOUTH_CAROLINA', 'South Carolina'),
    ('SOUTH_DAKOTA', 'South Dakota'),
    ('TENNESSEE', 'Tennessee'),
    ('TEXAS', 'Texas'),
    ('UTAH', 'Utah'),
    ('VERMONT', 'Vermont'),
    ('VIRGINIA', 'Virginia'),
    ('WASHINGTON', 'Washington'),
    ('WEST_VIRGINIA', 'West Virginia'),
    ('WISCONSIN', 'Wisconsin'),
    ('WYOMING', 'Wyoming'),
)

JOB_TYPES = (
    ('FULL_TIME', 'Full-time'),
    ('PART_TIME', 'Part-time'),
    ('TEMPORARY', 'Temporary'),
    ('COMMISSION', 'Commission'),
    ('CONTRACT', 'Contract'),
    ('INTERNSHIP', 'Internship'),
)